# Generated by Django 2.0.6 on 2018-08-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180823_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(blank=True, null=True, to='home.Categoria'),
        ),
    ]
